import Nav from './Nav'
import Footer from './Footer'
import Head from 'next/head'

export default function Layout({ children }: {children:any}) {
  return (
    <>
       <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>{children}</main>
      <Footer />
    </>
  )
}